/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	G:/caotai_code/td_prj/caotai_v1_0/ip/fmap_dram_256bit/fmap_dram_256bit.v
 ** Date	:	2023 10 30
 ** TD version	:	4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module fmap_dram_256bit ( di, waddr, we, wclk, do, raddr );

	parameter DATA_WIDTH_W = 256; 
	parameter ADDR_WIDTH_W = 5;
	parameter DATA_DEPTH_W = 32;
	parameter DATA_WIDTH_R = 256;
	parameter ADDR_WIDTH_R = 5;
	parameter DATA_DEPTH_R = 32;

	input  [DATA_WIDTH_W-1:0] di;
	input  [ADDR_WIDTH_W-1:0] waddr;
	input  [ADDR_WIDTH_R-1:0] raddr;
	input  wclk,we;

	output [DATA_WIDTH_R-1:0] do;



	EG_LOGIC_DRAM #(
 			.INIT_FILE("NONE"),
			.DATA_WIDTH_W(DATA_WIDTH_W),
			.ADDR_WIDTH_W(ADDR_WIDTH_W),
			.DATA_DEPTH_W(DATA_DEPTH_W),
			.DATA_WIDTH_R(DATA_WIDTH_R),
			.ADDR_WIDTH_R(ADDR_WIDTH_R),
			.DATA_DEPTH_R(DATA_DEPTH_R))
		dram(
			.di(di),
			.waddr(waddr),
			.wclk(wclk),
			.we(we),
			.do(do),
			.raddr(raddr));

endmodule