# This file is generated by Anlogic Timing Wizard. 16 12 2023

#Created Clock
create_clock -name clkin -period 40 -waveform {20 40} [get_ports {sys_clk}] -add

#Created Generated Clock
create_generated_clock  -add -name clk72 -source [get_ports {sys_clk}] -master_clock clkin -multiply_by 3 -duty_cycle 50 [get_nets {clk_72m}]
create_generated_clock  -add -name clk48 -source [get_ports {sys_clk}] -master_clock clkin -multiply_by 2 -duty_cycle 50 [get_nets {clk_48m}]
create_generated_clock  -add -name clk04 -source [get_ports {sys_clk}] -master_clock clkin -divide_by 6 -duty_cycle 50 [get_nets {clk_4m}]


