/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	G:/caotai_code/td_prj/caotai_v1_0/ip/algorithm_cmd_fifo_72bit/algorithm_cmd_fifo_72bit.v
 ** Date	:	2023 10 30
 ** TD version	:	4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module algorithm_cmd_fifo_72bit (
	rst,
	di, clkw, we,
	do, clkr, re,
	empty_flag,
	full_flag 
);

	input rst;
	input [71:0] di;
	input clkw, we;
	input clkr,re;

	output [71:0] do;
	output empty_flag;
	output full_flag;

EG_LOGIC_FIFO #(
 	.DATA_WIDTH_W(72),
	.DATA_WIDTH_R(72),
	.DATA_DEPTH_W(512),
	.DATA_DEPTH_R(512),
	.REGMODE_R("OUTREG"),
	.ENDIAN("BIG"),
	.RESETMODE("ASYNC"),
	.E(0),
	.F(512),
	.ASYNC_RESET_RELEASE("SYNC"))
logic_fifo(
	.rst(rst),
	.di(di),
	.clkw(clkw),
	.we(we),
	.csw(3'b111),
	.do(do),
	.clkr(clkr),
	.re(re),
	.csr(3'b111),
	.ore(1'b1),
	.empty_flag(empty_flag),
	.aempty_flag(),
	.full_flag(full_flag),
	.afull_flag()

);

endmodule