/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	G:/caotai_code/td_prj/caotai_v1_0/ip/para_rom_512bit/para_rom_512bit.v
 ** Date	:	2023 10 30
 ** TD version	:	4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module para_rom_512bit ( doa, addra, clka, rsta );

	output [511:0] doa;

	input  [8:0] addra;
	input  clka;
	input  rsta;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(512),
				.ADDR_WIDTH_A(9),
				.DATA_DEPTH_A(512),
				.DATA_WIDTH_B(512),
				.ADDR_WIDTH_B(9),
				.DATA_DEPTH_B(512),
				.MODE("SP"),
				.REGMODE_A("OUTREG"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("../../rtl/para.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia({512{1'b0}}),
				.dib({512{1'b0}}),
				.addra(addra),
				.addrb({9{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(1'b1),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule