/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	G:/caotai_code/td_prj/caotai_v1_0/ip/mult_16_16bit_signed/mult_16_16bit_signed.v
 ** Date	:	2023 10 30
 ** TD version	:	4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module mult_16_16bit_signed ( p, a, b, cea, ceb, cepd, clk, rstan, rstbn, rstpdn );

	output [31:0] p;

	input  [15:0] a;
	input  [15:0] b;
	input  cea;
	input  ceb;
	input  cepd;
	input  clk;
	input  rstan;
	input  rstbn;
	input  rstpdn;



	EG_LOGIC_MULT #( .INPUT_WIDTH_A(16),
				.INPUT_WIDTH_B(16),
				.OUTPUT_WIDTH(32),
				.INPUTFORMAT("SIGNED"),
				.INPUTREGA("ENABLE"),
				.INPUTREGB("ENABLE"),
				.OUTPUTREG("ENABLE"),
				.IMPLEMENT("AUTO"),
				.SRMODE("SYNC")

			)
			inst(
				.a(a),
				.b(b),
				.p(p),
				.cea(cea),
				.ceb(ceb),
				.cepd(cepd),
				.clk(clk),
				.rstan(rstan),
				.rstbn(rstbn),
				.rstpdn(rstpdn)
			);


endmodule